config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :post_tag_relations, dependent: :destroy
  #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :post_tag_relations, dependent: :destroy
end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :tag, optional: true
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :post_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :posts, through: :post_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable             
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post, dependent: :destroy
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(post_id: params[:post_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
    def index
        @posts = Post.all
        if params[:tag_ids]
          @posts = []
          params[:tag_ids].each do |key, value|      
            @posts += Tag.find_by(name: key).posts if value == "1"
          end
          @posts.uniq!
        end
    end
    def toyo
      @posts = Post.all
    end
  
    def nanyo
      @posts = Post.all
    end
  
    def midterm
      @posts = Post.all
    end
    

      def show
        @post = Post.find(params[:id])
      end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trip</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/4337792f41.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <header>
  <h1>trip</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>
</body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/posts/index.html.erb
<div class="mikyan">
<h1>trip</h1>
<h3>一覧ページ</h3>
<div class="scenery">
<div class="posts-container">
  <% @posts.each do |t| %>
    <% if t.category == "東予" %>
      <div class="post">
        <%= t.name %>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
              <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% else %>
              <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
        <%= link_to "詳細へ", post_path(t.id) %>
      </div>
   
   
    <% end %>
   
  <% end %>
</div>

<div class="posts-container">
  <% @posts.each do |t| %>
    <% if t.category == "中予" %>
      <div class="post">
        <%= t.name %>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
              <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% else %>
              <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
        <%= link_to "詳細へ", post_path(t.id) %>
      </div>
    <% end %>
  <% end %>
</div>
<div class="posts-container">
  <% @posts.each do |t| %>
    <% if t.category == "南予" %>
      <div class="post">
        <%= t.name %>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
              <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% else %>
              <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
        <%= link_to "詳細へ", post_path(t.id) %>
      </div>
    <% end %>
  <% end %>
</div>
</div>
<div class="scenery">
<div class="posts-container">
  <% @posts.each do |t| %>
    <% if t.category == "グルメ" %>
      <div class="post">
        <%= t.name %>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
              <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% else %>
              <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
        <%= link_to "詳細へ", post_path(t.id) %>
      </div>
    <% end %>
  <% end %>
</div>
<div class="posts-container">
  <% @posts.each do |t| %>
    <% if t.category == "お土産" %>
      <div class="post">
        <%= t.name %>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
              <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% else %>
              <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
        <%= link_to "詳細へ", post_path(t.id) %>
      </div>
    <% end %>
  <% end %>
</div>
<div class="posts-container">
  <% @posts.each do |t| %>
    <% if t.category == "イベント" %>
      <div class="post">
        <%= t.name %>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
              <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% else %>
              <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
        <%= link_to "詳細へ", post_path(t.id) %>
      </div>
    <% end %>
  <% end %>
</div>
</div>
<%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
  <% Tag.all.each do |t| %>
      <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
  <% end %>
  <%= submit_tag '検索' %>
<% end %>
</div>

app/views/posts/midterm.html.erb
<h1>中予</h1>
<% @posts.each do |t| %>
  <% if t.category == "midterm" %>  #ここがポイント！ categoryカラムにdogと格納されているものだけを表示している！
  <p>内容:<%= t.content %></p>
  <% end %>
<% end %>

app/views/posts/nanyo.html.erb
<h1>南予</h1>
<% @posts.each do |t| %>
  <% if t.category == nanyo" %>  #ここがポイント！ categoryカラムにdogと格納されているものだけを表示している！
  <p>内容:<%= t.content %></p>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<h1>trip</h1>
<h3>post詳細</h3>
<div class="post">
  <p><%= @post.name %></p>
  <img src="<%=@post.image%>">
  <p><%= @post.sentence %></p>
  <a href = "<%= @post.link %>">公式ホームページ</a>
  <p><%= @post.created_at %></p>
   <% if user_signed_in? %>
    <% if current_user.already_liked?(@post) %>
     <%= link_to post_like_path(@post), method: :delete do %>
      <i class="fas fa-heart"></i><%= @post.likes.count %>
      <% end %>
     <% else %>
      <%= link_to post_likes_path(@post), method: :post do %>
        <i class="far fa-heart"></i><%= @post.likes.count %>
      <% end %>
     <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= @post.likes.count %>
    <% end %>
</div>

<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<%= link_to "Post一覧に戻る", posts_path %>

<% @post.tags.each do |tag| %>
  <span><%= tag.name %></span>
<% end %>

app/views/posts/toyo.html.erb
<h1>東予</h1>
<% @posts.each do |t| %>
  <% if t.category == "toyo" %>  #ここがポイント！ categoryカラムにdogと格納されているものだけを表示している！
  <p>内容:<%= t.content %></p>
  <% end %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>